# Pod Identity Association is created separately outside of this chart
# Use AWS CLI to create it:
# aws eks create-pod-identity-association \
#   --cluster-name <cluster-name> \
#   --namespace <namespace> \
#   --service-account <service-account-name> \
#   --role-arn <iam-role-arn>
