{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "go-htmx-fiber.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "go-htmx-fiber.labels" . | nindent 4 }}
  annotations:
    {{- if and .Values.podIdentity.enabled .Values.podIdentity.roleArn }}
    eks.amazonaws.com/pod-identity-role-arn: {{ .Values.podIdentity.roleArn }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
